/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package abic.tas.assetTicket.struts.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-14-2014
 * 
 * XDoclet definition:
 * @struts.form name="inserisciAssetForm"
 */
public class InserisciAssetForm extends ActionForm {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String tipoAsset;
	private String proprieta;
	
	private String ubicazione;
	private String posizione;
	private String tipo_utilizzo;
	private String utilizzo;
	private String categoria;
	private String macro_tipologia;
	private String tipologia;
	private String sotto_categoria;
	
	private String stato;
	private String marca;
	private String id_old;
	private String modello;
	private String id;
	private String seriale;
	private String etichetta;
	private String valore_listino;

	private String consumo_nominale;
	private String consumo_misurato;
	private String fascia_consumo_opex;
	private String opex;
	
	private String ip;
	private String dati_contrattuali;
	private String on_off;
	private String username;
	private String password;
	private String servizio;
	private String payed;
	private String migrazione;
	private String vnx;
	private String telecom_asset_id;
	/**
	 * @return the tipoAsset
	 */
	public String getTipoAsset() {
		return tipoAsset;
	}
	/**
	 * @param tipoAsset the tipoAsset to set
	 */
	public void setTipoAsset(String tipoAsset) {
		this.tipoAsset = tipoAsset;
	}
	/**
	 * @return the proprieta
	 */
	public String getProprieta() {
		return proprieta;
	}
	/**
	 * @param proprieta the proprieta to set
	 */
	public void setProprieta(String proprieta) {
		this.proprieta = proprieta;
	}
	/**
	 * @return the ubicazione
	 */
	public String getUbicazione() {
		return ubicazione;
	}
	/**
	 * @param ubicazione the ubicazione to set
	 */
	public void setUbicazione(String ubicazione) {
		this.ubicazione = ubicazione;
	}
	/**
	 * @return the posizione
	 */
	public String getPosizione() {
		return posizione;
	}
	/**
	 * @param posizione the posizione to set
	 */
	public void setPosizione(String posizione) {
		this.posizione = posizione;
	}
	/**
	 * @return the tipo_utilizzo
	 */
	public String getTipo_utilizzo() {
		return tipo_utilizzo;
	}
	/**
	 * @param tipo_utilizzo the tipo_utilizzo to set
	 */
	public void setTipo_utilizzo(String tipo_utilizzo) {
		this.tipo_utilizzo = tipo_utilizzo;
	}
	/**
	 * @return the utilizzo
	 */
	public String getUtilizzo() {
		return utilizzo;
	}
	/**
	 * @param utilizzo the utilizzo to set
	 */
	public void setUtilizzo(String utilizzo) {
		this.utilizzo = utilizzo;
	}
	/**
	 * @return the categoria
	 */
	public String getCategoria() {
		return categoria;
	}
	/**
	 * @param categoria the categoria to set
	 */
	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}
	/**
	 * @return the macro_tipologia
	 */
	public String getMacro_tipologia() {
		return macro_tipologia;
	}
	/**
	 * @param macro_tipologia the macro_tipologia to set
	 */
	public void setMacro_tipologia(String macro_tipologia) {
		this.macro_tipologia = macro_tipologia;
	}
	/**
	 * @return the tipologia
	 */
	public String getTipologia() {
		return tipologia;
	}
	/**
	 * @param tipologia the tipologia to set
	 */
	public void setTipologia(String tipologia) {
		this.tipologia = tipologia;
	}
	/**
	 * @return the sotto_categoria
	 */
	public String getSotto_categoria() {
		return sotto_categoria;
	}
	/**
	 * @param sotto_categoria the sotto_categoria to set
	 */
	public void setSotto_categoria(String sotto_categoria) {
		this.sotto_categoria = sotto_categoria;
	}
	/**
	 * @return the stato
	 */
	public String getStato() {
		return stato;
	}
	/**
	 * @param stato the stato to set
	 */
	public void setStato(String stato) {
		this.stato = stato;
	}
	/**
	 * @return the marca
	 */
	public String getMarca() {
		return marca;
	}
	/**
	 * @param marca the marca to set
	 */
	public void setMarca(String marca) {
		this.marca = marca;
	}
	/**
	 * @return the id_old
	 */
	public String getId_old() {
		return id_old;
	}
	/**
	 * @param id_old the id_old to set
	 */
	public void setId_old(String id_old) {
		this.id_old = id_old;
	}
	/**
	 * @return the modello
	 */
	public String getModello() {
		return modello;
	}
	/**
	 * @param modello the modello to set
	 */
	public void setModello(String modello) {
		this.modello = modello;
	}
	/**
	 * @return the id
	 */
	public String getId() {
		return id;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(String id) {
		this.id = id;
	}
	/**
	 * @return the seriale
	 */
	public String getSeriale() {
		return seriale;
	}
	/**
	 * @param seriale the seriale to set
	 */
	public void setSeriale(String seriale) {
		this.seriale = seriale;
	}
	/**
	 * @return the etichetta
	 */
	public String getEtichetta() {
		return etichetta;
	}
	/**
	 * @param etichetta the etichetta to set
	 */
	public void setEtichetta(String etichetta) {
		this.etichetta = etichetta;
	}
	/**
	 * @return the valore_listino
	 */
	public String getValore_listino() {
		return valore_listino;
	}
	/**
	 * @param valore_listino the valore_listino to set
	 */
	public void setValore_listino(String valore_listino) {
		this.valore_listino = valore_listino;
	}
	/**
	 * @return the consumo_nominale
	 */
	public String getConsumo_nominale() {
		return consumo_nominale;
	}
	/**
	 * @param consumo_nominale the consumo_nominale to set
	 */
	public void setConsumo_nominale(String consumo_nominale) {
		this.consumo_nominale = consumo_nominale;
	}
	/**
	 * @return the consumo_misurato
	 */
	public String getConsumo_misurato() {
		return consumo_misurato;
	}
	/**
	 * @param consumo_misurato the consumo_misurato to set
	 */
	public void setConsumo_misurato(String consumo_misurato) {
		this.consumo_misurato = consumo_misurato;
	}
	/**
	 * @return the fascia_consumo_opex
	 */
	public String getFascia_consumo_opex() {
		return fascia_consumo_opex;
	}
	/**
	 * @param fascia_consumo_opex the fascia_consumo_opex to set
	 */
	public void setFascia_consumo_opex(String fascia_consumo_opex) {
		this.fascia_consumo_opex = fascia_consumo_opex;
	}
	/**
	 * @return the opex
	 */
	public String getOpex() {
		return opex;
	}
	/**
	 * @param opex the opex to set
	 */
	public void setOpex(String opex) {
		this.opex = opex;
	}
	/**
	 * @return the ip
	 */
	public String getIp() {
		return ip;
	}
	/**
	 * @param ip the ip to set
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}
	/**
	 * @return the dati_contrattuali
	 */
	public String getDati_contrattuali() {
		return dati_contrattuali;
	}
	/**
	 * @param dati_contrattuali the dati_contrattuali to set
	 */
	public void setDati_contrattuali(String dati_contrattuali) {
		this.dati_contrattuali = dati_contrattuali;
	}
	/**
	 * @return the on_off
	 */
	public String getOn_off() {
		return on_off;
	}
	/**
	 * @param on_off the on_off to set
	 */
	public void setOn_off(String on_off) {
		this.on_off = on_off;
	}
	/**
	 * @return the username
	 */
	public String getUsername() {
		return username;
	}
	/**
	 * @param username the username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}
	/**
	 * @return the password
	 */
	public String getPassword() {
		return password;
	}
	/**
	 * @param password the password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}
	/**
	 * @return the servizio
	 */
	public String getServizio() {
		return servizio;
	}
	/**
	 * @param servizio the servizio to set
	 */
	public void setServizio(String servizio) {
		this.servizio = servizio;
	}
	/**
	 * @return the payed
	 */
	public String getPayed() {
		return payed;
	}
	/**
	 * @param payed the payed to set
	 */
	public void setPayed(String payed) {
		this.payed = payed;
	}
	/**
	 * @return the migrazione
	 */
	public String getMigrazione() {
		return migrazione;
	}
	/**
	 * @param migrazione the migrazione to set
	 */
	public void setMigrazione(String migrazione) {
		this.migrazione = migrazione;
	}
	/**
	 * @return the vnx
	 */
	public String getVnx() {
		return vnx;
	}
	/**
	 * @param vnx the vnx to set
	 */
	public void setVnx(String vnx) {
		this.vnx = vnx;
	}
	/**
	 * @return the telecom_asset_id
	 */
	public String getTelecom_asset_id() {
		return telecom_asset_id;
	}
	/**
	 * @param telecom_asset_id the telecom_asset_id to set
	 */
	public void setTelecom_asset_id(String telecom_asset_id) {
		this.telecom_asset_id = telecom_asset_id;
	}
	/**
	 * @return the serialversionuid
	 */
	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	
	
}