/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package abic.tas.assetTicket.asset.struts.action;

import java.util.List;

import javax.jms.Session;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import abic.tas.assetTicket.admin.bean.adminAssetBean;
import abic.tas.assetTicket.admin.struts.action.AdminAssetHomeAction;
import abic.tas.assetTicket.hibernate.CategoriaDAO;


/** 
 * MyEclipse Struts
 * Creation date: 01-14-2014
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="successAdminCreaAsset" path="/WEB-INF/main/jsp/admin/asset/creaAsset.jsp"
 */
public class AdminCreaAssetAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		return mapping.findForward("successAdminCreaAsset");
	}
}