/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package abic.tas.assetTicket.asset.struts.action;


import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import abic.tas.assetTicket.hibernate.AssetDAO;
import abic.tas.assetTicket.hibernate.AssetFisico;
import abic.tas.assetTicket.hibernate.AssetFisicoDAO;
import abic.tas.assetTicket.struts.form.InserisciAssetForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-14-2014
 * 
 * XDoclet definition:
 * @struts.action path="/inserisciAsset" name="inserisciAssetForm" input="/form/inserisciAsset.jsp" scope="request" validate="true"
 */
public class InserisciAssetAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		InserisciAssetForm inserisciAssetForm = (InserisciAssetForm) form;// TODO Auto-generated method stub

		
		// validazione dei dati che sono stati inseriti
		//validazione();
		
		
		//inserimento dei dati all'interno dell db
		
		
		AssetFisicoDAO assetFisico= new AssetFisicoDAO();
		
		AssetFisico dati = new AssetFisico();
		dati.setProprieta(inserisciAssetForm.getProprieta());
	//	dati.setUbicazione(inserisciAssetForm.getUbicazione());
//		dati.setPosizione(inserisciAssetForm.getPosizione());
//		dati.setIdOwner("lahridi");
//		dati.setIdRiferimento("mouhsine");
		dati.setUtilizzoProgetto(inserisciAssetForm.getTipo_utilizzo());
		dati.setUtilizzoProgetto("abic");
//		dati.setCategoriaByIdCategoria(inserisciAssetForm.getCategoria());
//		dati.setCategoriaByIdSottoCategoria(inserisciAssetForm.getSotto_categoria());
//		dati.setCategoriaByIdMacroTipologia(inserisciAssetForm.getMacro_tipologia());
//		dati.setCategoriaByIdTipologia(inserisciAssetForm.getTipologia());
//		dati.setDispositivo(inserisciAssetForm.getId());
		assetFisico.save(dati);
		
		return null;
		
	}
	
	@SuppressWarnings("unused")
	private void validazione(){
		InserisciAssetForm dati = new InserisciAssetForm();
		
		
		if (!dati.getProprieta().isEmpty() && (!dati.getProprieta().equals(null))){
			if(!dati.getUbicazione().isEmpty()){
				if (!dati.getPosizione().isEmpty()){
					if (!dati.getTipo_utilizzo().isEmpty()){
						if (!dati.getUtilizzo().isEmpty()){
							if (!dati.getCategoria().isEmpty()){
								if (!dati.getMacro_tipologia().isEmpty()){
									if (!dati.getTipologia().isEmpty()){
										if (!dati.getSotto_categoria().isEmpty()){
											if (!dati.getStato().isEmpty()){
												if (!dati.getMarca().isEmpty()){
													if (!dati.getId_old().isEmpty()){
														if (!dati.getModello().isEmpty()){
															if (!dati.getId().isEmpty()){
																if (!dati.getSeriale().isEmpty()){
																	if (!dati.getUtilizzo().isEmpty()){
																		if (!dati.getEtichetta().isEmpty()){
																			if (!dati.getValore_listino().isEmpty()){
																				if (!dati.getConsumo_nominale().isEmpty()){
																					if (!dati.getConsumo_misurato().isEmpty()){
																						if (!dati.getFascia_consumo_opex().isEmpty()){
																							if (!dati.getOpex().isEmpty()){
																								if (!dati.getIp().isEmpty()){
																									if (!dati.getDati_contrattuali().isEmpty()){
																										if (!dati.getOn_off().isEmpty()){
																											if (!dati.getUsername().isEmpty()){
																												if (!dati.getPassword().isEmpty()){
																													if (!dati.getServizio().isEmpty()){
																														if (!dati.getPayed().isEmpty()){
																															if (!dati.getMigrazione().isEmpty()){
																																if (!dati.getVnx().isEmpty()){
																																	if (!dati.getTelecom_asset_id().isEmpty()){
																																		AssetDAO asset = new AssetDAO();
																																		
																																	}
																																}
																															}
																														}
																													}
																												}
																											}
																										}
																									}
																								}
																							}
																						}
																					}
																				}
																			}																																					
																		}
																	}
																}
															}
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}

		
		
	}
}